apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 60m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  timeout: 5m
  interval: 60m
  chart:
    spec:
      chart: crossplane
      version: '1.18.0'
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
      interval: 60m

